services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: pollapp
    ports:
      - "5432:5432"
    restart: always

  pollapp:
    build:
      context: .
      dockerfile: pollapp.Dockerfile
    container_name: pollapp
    depends_on:
      - redis
      - rabbitmq
      - postgres
    environment:
      APP_REDIS_URL: redis://redis:6379
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pollapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecret
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: frontend
    depends_on:
      - pollapp
    ports:
      - "80:80"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

